name: Build and Publish Docker Image

on:
  push:
    branches:
      - 'main'
  pull_request:

env:
  IMAGE: registry.indicareleve.me/indicareleve

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Generate build ID
      id: prep
      run: echo "BUILD_ID=$(date +%s)" >> $GITHUB_ENV     

    - name: Checkout
      uses: actions/checkout@v3

    - name: Log in to private registry
      uses: docker/login-action@v2
      with:
        registry: https://registry.indicareleve.me
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - name: Build and push testing
      if: github.event_name == 'pull_request'
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: |
              ${{ env.IMAGE }}:${{ env.BUILD_ID }}-testing-${{ github.event.pull_request.head.ref }}
              ${{ env.IMAGE }}:testing

    - name: Build and push prod
      if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: |
              ${{ env.IMAGE }}:${{ env.BUILD_ID }}
              ${{ env.IMAGE }}:latest
